Repository dotnet/AspNetCore.Docs, pull requests merged in 2019-10, with the labels that each got.

#14748 Removed instruction to accept privacy policy
  aspnetcore/getting-started/index.md
Labels: P2

#14812 Update SignalR tutorial to 3.0 - startup.cs - additional screenshots
  aspnetcore/tutorials/signalr.md
  aspnetcore/tutorials/signalr/_static/2.x/f12-console.png
  aspnetcore/tutorials/signalr/_static/2.x/libman1.png
  aspnetcore/tutorials/signalr/_static/2.x/libman2.png
  aspnetcore/tutorials/signalr/_static/2.x/signalr-get-started-finished.png
  aspnetcore/tutorials/signalr/_static/2.x/signalr-new-project-choose-type.png
  aspnetcore/tutorials/signalr/_static/2.x/signalr-new-project-dialog.png
  aspnetcore/tutorials/signalr/_static/3.x/f12-console.png
  aspnetcore/tutorials/signalr/_static/3.x/signalr-get-started-finished.png
  aspnetcore/tutorials/signalr/_static/3.x/signalr-new-project-dialog.png
  aspnetcore/tutorials/signalr/sample-snapshot/2.x/ChatHub.cs
  aspnetcore/tutorials/signalr/sample-snapshot/2.x/Index.cshtml
  aspnetcore/tutorials/signalr/sample-snapshot/2.x/Startup.cs
  aspnetcore/tutorials/signalr/sample-snapshot/2.x/chat.js
  aspnetcore/tutorials/signalr/sample-snapshot/3.x/Index.cshtml
  aspnetcore/tutorials/signalr/sample-snapshot/3.x/Startup.cs
Labels: P1, in-progress

#14956 Updated signalr script tag (#14810)
  aspnetcore/tutorials/signalr.md
  aspnetcore/tutorials/signalr/sample-snapshot/3.x/Index.cshtml
Labels: SignalR
