Repository dotnet/AspNetCore.Docs, pull requests merged in 2019-09, with the labels that each got.

#14115 Add note about SVG. Fixes #13931
  aspnetcore/blazor/components.md
Labels: Blazor

#14036 Change Tokens topic update for 3.0
  aspnetcore/fundamentals/change-tokens.md
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/ChangeTokenSample.csproj
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Extensions/ConfigurationMonitor.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/Error.cshtml
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/Error.cshtml.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/Index.cshtml
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/Index.cshtml.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/Shared/_Layout.cshtml
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/_ViewImports.cshtml
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Pages/_ViewStart.cshtml
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Program.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/README.md
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Services/FileService.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Startup.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/Utilities/Utilities.cs
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/appsettings.Development.json
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/appsettings.Production.json
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/appsettings.json
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/poem.txt
  aspnetcore/fundamentals/change-tokens/samples/3.x/SampleApp/wwwroot/images/console-config-change.png
Labels: PU

#14108 Updates for side-by-side and web root references
  aspnetcore/fundamentals/index.md
  aspnetcore/includes/benefits.md
  aspnetcore/index.md
Labels: 3.0

#14200 Link fix related to 14108
  aspnetcore/fundamentals/index.md
Labels: 3.0

#14481 Update ASP.NET Core Get Started for 3.0
  aspnetcore/getting-started/index.md
Labels: 3.0

#14543 Added link for YouTube version
  aspnetcore/tutorials/signalr.md
Labels: SignalR

#12270 Link and Script TH
  aspnetcore/includes/built-in-TH.md
  aspnetcore/includes/cdn.md
  aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper.md
  aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/HtmlPage1.html
  aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/HtmlPage2.html
  aspnetcore/mvc/views/tag-helpers/built-in/link-tag-helper/sample/_Layout.cshtml
  aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md
Labels: PU

#14644 Updated with dotnet watch run and browser refresh
  aspnetcore/getting-started/index.md
Labels: doc-bug
